<ul class="form-list">
    <li>
        <label for="partner_of_shopping" class="required"><em>*</em><?php echo $this->__('Partner of shopping') ?></label>
        <div class="input-box">
            <input form="form-validate" type="text" name="partner_of_shopping" id="partner_of_shopping" value="<?php echo ($partner = $this->getCustomer()->getPartnerOfShopping())?$partner:'' ?>" title="<?php echo $this->__('Partner of shopping') ?>" class="input-text required-entry validate-email" />
        </div>
    </li>
</ul>