<?php if($partner = $this->getCustomer()->getPartnerOfShopping()): ?>
    <div class="box-account box-info">
        <div class="col2-set">
            <div class="col-1">
                <div class="box">
                    <div class="box-title">
                        <h3><?php echo $this->__('Partner of shopping') ?></h3>
                    </div>
                    <div class="box-content">
                        <p><?php echo $partner ?></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>